# Zadanie pre certifikáciu

## Téma projektu

V tomto projekte sa budeme venovať **predikciám odchodu klientov z banky** (tzv. customer churn prediction). 

Budeme pracovať s datasetom, ktorý obsahuje informácie o bankových klientoch. Našou úlohou bude vytvoriť model, ktorý dokáže predpovedať, či klient z banky odíde alebo nie.

Keď klient opustí banku, znamená to stratu:

* pravidelných príjmov z poplatkov,
* ako aj stratu potenciálnych príležitostí pre predaj ďalších produktov ako hypotéky či investície.

Keď banka dokáže včas rozpoznať rizikových klientov, môže s nimi aktívne pracovať - napríklad im ponúknuť lepšie podmienky alebo skvalitniť poskytované služby. Tým sa zvýši ich spokojnosť a šanca, že v banke zostanú.

Pozrime sa na vstupné údaje, ktoré budete používať v tomto projekte:

## Dataset

* Dataset je dostupný v súbore:
    * `bank_customer_churn_dataset/data.csv` (je umiestnený hneď vedľa Python notebooku)
* Celkový počet stĺpcov v datasete je 12
    * Počet prediktorov: 11
    * Cieľový stĺpec (target): `churn`

Kľúčová premenná, ktorú budeme predikovať, je stĺpec `churn`:

- `churn = 1`: klient odišiel z banky (zrušil všetky produkty a služby)
- `churn = 0`: klient zostal aktívnym klientom banky

**Popis stĺpcov**

| Premenná | Stručný popis | Detailnejší popis |
|:----------|:-------------|:---------|
| `customer_id` | Jedinečný identifikátor každého zákazníka | Unikátne číslo priradené každému klientovi banky pre jeho jednoznačnú identifikáciu |
| `credit_score` | Kreditné skóre zákazníka | Číselné hodnotenie bonity klienta, ktoré vyjadruje jeho schopnosť splácať záväzky. Vyššie skóre znamená nižšie riziko pre banku |
| `country` | Krajina zákazníka | Krajina trvalého pobytu klienta (Francúzsko, Španielsko, Nemecko). Umožňuje analyzovať geografické rozdiely v správaní klientov |
| `gender` | Pohlavie zákazníka | Pohlavie klienta (Muž/Žena). Môže pomôcť identifikovať rozdiely v správaní medzi pohlaviami |
| `age` | Vek zákazníka v rokoch | Vek klienta v čase zberu dát. Dôležitý faktor pre pochopenie vekových skupín a ich tendencie k odchodu |
| `tenure` | Počet rokov ako klient banky | Dĺžka vzťahu s bankou v rokoch. Indikuje lojalitu zákazníka a stabilitu vzťahu |
| `balance` | Zostatok na účte | Aktuálny zostatok na všetkých účtoch klienta v banke. Vyjadruje finančnú aktivitu klienta |
| `products_number` | Počet využívaných bankových produktov | Počet rôznych produktov, ktoré klient aktívne využíva (účty, karty, poistenia, úvery). Ukazuje mieru angažovanosti klienta |
| `credit_card` | Či má zákazník kreditnú kartu | Indikátor (1=Áno, 0=Nie) vlastníctva kreditnej karty. Dôležitý ukazovateľ využívania úverových produktov |
| `active_member` | Či je zákazník aktívnym členom | Indikátor (1=Áno, 0=Nie) aktivity klienta. Aktívny klient pravidelne využíva bankové služby |
| `estimated_salary` | Odhadovaný ročný príjem | Odhadovaný ročný príjem klienta. Kľúčový ukazovateľ finančnej situácie klienta |
| `churn` | Či zákazník odišiel | Cieľová premenná (1=Áno, 0=Nie) indikujúca, či klient ukončil svoje služby v banke |

Viac informácií k tomuto datasetu nie je, teda je nutné si vystačiť s týmito informáciami, ktoré sú dostupné.

Hlavným cieľom je vytvoriť ML model, ktorý bude robiť predikcie, či klient z banky odíde alebo nie. 
V procese vytvárania modelu sa ukáže, ako dobre rozumiete základom Machine Learningu a dokážete tieto znalosti prakticky použiť. Máte relatívnu voľnosť v tom, ako budete postupovať, je potrebné však dbať, aby ste nezabudli na základné požiadavky nižšie.

## Základné požiadavky

Toto je základný zoznam krokov, ktoré by vaše riešenie malo obsahovať:

1. **Načítanie dát**
   - Načítajte dáta zo vstupného súboru
2. **Základná EDA (Exploratory Data Analysis)**
   - Zistite koľko máte dát
   - Skontrolujte či chýbajú nejaké údaje a keď áno tak koľko
   - Identifikujte aké máte typy údajov.
       - Je dôležité si uvedomiť, aký skutočný typ sa v každom stĺpci nachádza = tzn. či je to skutočné číslo alebo kategória (nominálna / ordinálna) alebo dátum / čas atď...
       - Niekdy môže byť v dátach - v stĺpci zdanlivo obyčajné číslo, ale skutočný logický typ daného stĺpca môže byť kategorický. Dajte si na to pozor.
3. **Data splits**
    - Predictors / target split
    - Train / test split
4. **Vytvorenie modelu / pipeline**
   - Vytvorte pipeline, ktorá bude konvertovať vstupné dáta do číselného formátu vhodného pre modelovanie
   - Konkrétny výber modelu v poslednom kroku pipeline je na vás - môžete si vybrať akýkoľvek klasifikačný model typu Rozhodovací strom (napr. DecisionTreeClassifier, RandomForestClassifier alebo XGBoostClassifier)
5. **Model Tuning**
   - Očakáva sa aspoň jednoduchý Model Tuning, kde sa pokúsite nájsť najlepšie nastavenia modelu
   - Aké nastavenia modelu budete ladiť a aké hodnoty - to je na vás, môžete sa sami rozhodnúť
6. **Model Serialization**
   - Keď budete mať model s najlepšími nastaveniami, bolo by dobré ho uložiť na disk, aby sa dal v prípade potreby načítať z disku a použiť neskôr bez nutnosti opätovného trénovania
7. **Model Evaluation**
   - Spravte vyhodnotenie presnosti modelu na testovacej vzorke. Sami si zvoľte metriku/y, ktoré uznáte za vhodné.
   - Radi by sme videli aj aké faktory (stĺpce) v dátach boli pre model najdôležitejšie - tzn. `feature importance`.
8. **Self-assessment**
   - V tomto kroku spravte krátku seba-reflexiu:
       - Voliteľné: Ako ste podľa vás skúšku zvládli, čo boli ľahšie / ťažšie časti
       - Povinné: Aké hodnotenie by ste si férovo sami dali, keby ste sami mali dať finálnu známku medzi 0 - 100%

Toto je teda nutné minimum. Keď v tomto rozsahu zvládnete všetko v poriadku, úplne to postačí na 100% výsledok na tejto certifikácii.

## Poznámky

- Všetko ostatné, čo nie je špecifikované je voliteľné a je na vašom rozhodnutí, či urobíte niečo naviac nad rámec základných požiadaviek.
- Hodnotiť sa bude úroveň celého riešenia ako celku. Ak urobíte nejaké veci naviac (nad rámec základných požiadaviek vyššie), môžete tým čiastočne vykompenzovať menej závažné nedostatky / chyby, ktoré by sa v riešení mohli objaviť.
- Okrem písania samotného kódu veľmi oceníme, keď medzi kód napíšete aj vaše myšlienky / postrehy - ako v jednotlivých krokoch uvažujete alebo výsledky interpretujete atď. Pomôže nám to lepšie porozumieť ako ste uvažovali, čo ste mali na mysli a akým spôsobom nad vecami premýšľate.
    - Môžete používať angličtinu / slovenčinu podľa potreby (obidva jazyky sú OK)
    - Snažte sa o prehľadné a štruktúrované riešenie, v ktorom sa bude dať ľahko zorientovať. Výsledok vašej práce bude čítať a vyhodnocovať človek. Tam kde uznáte za vhodné, môžete pridať komentáre ku kódu alebo markdown bunky s textom.

Netreba mať žiadne obavy. V certifikácii nie sú žiadne prekvapenia, chytáky ani náročné časti.
Je tam len to, čo sme sa učili a čo sa očakáva, že by mal každý zvládnuť.

Držíme všetky palce 😊💪

---

---

Nasleduje riešenie projektu. Pripravili sme pre vás nadpisy, ktoré by vás mali preniesť základným postupom.
Môžete si tento postup upraviť / rozšíriť / prispôsobiť vašim potrebám. Je to len hrubá úvodná štruktúra, aby boli zrejmé základné požiadavky, ktoré od vás očakávame. Pokojne môžete pridať ďalšie nadpisy tak, aby vaše riešenie bolo prehľadné a štruktúrované.

# Solution

## Load data

In [15]:
# TODO
import pandas as pd

# Load data from CSV file
df=pd.read_csv('bank_customer_churn_dataset/data.csv')

# Preview data
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## EDA (Exploratory Data Analysis)

### Amount of data

What is the count of rows / columns in dataset?

In [16]:
# TODO
print(df.shape)

(10000, 12)

### Missing data

How many data are misssing?

In [17]:
df_missing = (
    df.isnull().sum()
    .to_frame('count')
    .assign(ratio = lambda dft: dft['count'] / len(df))
)

# Show nicely formatted DataFrame (with highlighted values above 0)
df_missing.style.format({'ratio': '{:.2%}'}).highlight_between(left=0, inclusive='neither')

### Data types

What are the types of data in individual columns?

In [18]:
# TODO
df.dtypes

customer_id           int64
credit_score          int64
country              object
gender               object
age                   int64
tenure                int64
balance             float64
products_number       int64
credit_card           int64
active_member         int64
estimated_salary    float64
churn                 int64
dtype: object

In [19]:
#only for quick check and investigation :

from ydata_profiling import ProfileReport

pp = ProfileReport(df)
pp.to_file("Report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████████████████████████████████████| 12/12 [00:00<00:00, 610.01it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## Data splits

### Predictors / target split

In [20]:
# TODO
# Predictors / Target split
x = df.iloc[:, :-1].copy()   
y = df.iloc[:, -1].copy()

### Train / test split

In [21]:
# TODO
#Train/Test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=999)

## Create model / pipeline

In [22]:
#Preprocessing data

# Columns we can delete (not predictive)
drop_columns=['customer_id']

# Columns representing nominal categories (for OneHot encoding)
category_nominal_columns= [
    'country','gender','products_number'
]

    
#Helper function
def remove_columns(x):
    x=x.copy()
    return x.drop(columns=drop_columns)

In [23]:
df.head(2)

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Helper function, that forces transformers to operate only on some columns, not whole dataframe
def per_column_transformers(transformers_list, remainder='passthrough'):
    return ColumnTransformer(transformers=transformers_list, remainder=remainder, verbose_feature_names_out=False)

# Create pipeline
pipeline = Pipeline(steps=[
    ('remove_columns', FunctionTransformer(remove_columns)), 
    ('per_column_transformers', per_column_transformers([
        ('convert_nominal_categories', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), category_nominal_columns)

    ])),
])

# Configure pipeline
pipeline.set_output(transform="pandas")

Pipeline(steps=[('remove_columns',
                 FunctionTransformer(func=<function remove_columns at 0x16cf1c180>)),
                ('per_column_transformers',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('convert_nominal_categories',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['country', 'gender',
                                                   'products_number'])],
                                   verbose_feature_names_out=False))])

In [25]:
x_train_transformed = pipeline.fit_transform(x_train)

# Check result
x_train_transformed.head(2)

,country_France,country_Germany,country_Spain,gender_Female,gender_Male,products_number_1,products_number_2,products_number_3,products_number_4,credit_score,age,tenure,balance,credit_card,active_member,estimated_salary
8007,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,647,41,4,138937.35,1,1,101617.64
9688,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,850,68,5,169445.40,1,1,186335.07

In [26]:
# Add model to pipeline:

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from xgboost import XGBClassifier

# Helper function, that forces transformers to operate only on some columns, not whole dataframe
def per_column_transformers(transformers_list, remainder='passthrough'):
    return ColumnTransformer(transformers=transformers_list, remainder=remainder, verbose_feature_names_out=False)

# Create pipeline
pipeline = Pipeline(steps=[
    ('remove_columns', FunctionTransformer(remove_columns)), 
    ('per_column_transformers', per_column_transformers([
        ('convert_nominal_categories', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), category_nominal_columns)
    ])),
    ('model', XGBClassifier(random_state=555))
])

# Configure pipeline
pipeline.set_output(transform="pandas")

Pipeline(steps=[('remove_columns',
                 FunctionTransformer(func=<function remove_columns at 0x16cf1c180>)),
                ('per_column_transformers',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('convert_nominal_categories',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['country', 'gender',
                                                   'products_number'])],
                                   verbose_feature_names_out=False)),
                ('mo...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

## Model Tuning

In [35]:
#Nem imports
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform

# Define the parameter space
param_dist = {
    'model__n_estimators': randint(300, 601),
    'model__max_depth': randint(3, 4),
    'model__learning_rate': uniform(0.01, 0.05),
    'model__colsample_bytree': uniform(0.2, 0.4)
}

# Set up RandomizedSearchCV
random_search = RandomizedSearchCV(pipeline, param_dist, n_iter=50, cv=10, scoring='roc_auc', random_state=341, n_jobs=-1)

# Fit the random search
random_search.fit(x_train, y_train)

RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('remove_columns',
                                              FunctionTransformer(func=<function remove_columns at 0x16cf1c180>)),
                                             ('per_column_transformers',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('convert_nominal_categories',
                                                                               OneHotEncoder(handle_unknown='ignore',
                                                                                             sparse_output=False),
                                                                               ['country',
                                                                                'gender',
                                                                                'products_number'])],
                                                                ver...
                   param_distributions={'model__colsample_bytree': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x16da24110>,
                                        'model__learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x16da27680>,
                                        'model__max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x16da27da0>,
                                        'model__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x16cca0aa0>},
                   random_state=341, scoring='roc_auc')

In [36]:
random_search.best_params_

{'model__colsample_bytree': np.float64(0.5945349994052989),
 'model__learning_rate': np.float64(0.030853386772093122),
 'model__max_depth': 3,
 'model__n_estimators': 560}

In [40]:
random_search.best_score_

np.float64(0.8653812941670529)

In [41]:
best_model=random_search.best_estimator_
best_model

Pipeline(steps=[('remove_columns',
                 FunctionTransformer(func=<function remove_columns at 0x16cf1c180>)),
                ('per_column_transformers',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('convert_nominal_categories',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['country', 'gender',
                                                   'products_number'])],
                                   verbose_feature_names_out=False)),
                ('mo...
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=np.float64(0.030853386772093122),
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=560, n_jobs=None,
                               num_parallel_tree=None, ...))])

## Model Serialization

In [42]:
import joblib 

joblib.dump(best_model, "model_xgb.pkl")

['model_xgb.pkl']

In [43]:
best_model=joblib.load("model_xgb.pkl")
best_model

Pipeline(steps=[('remove_columns',
                 FunctionTransformer(func=<function remove_columns at 0x16cf1c180>)),
                ('per_column_transformers',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('convert_nominal_categories',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['country', 'gender',
                                                   'products_number'])],
                                   verbose_feature_names_out=False)),
                ('mo...
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=np.float64(0.030853386772093122),
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=560, n_jobs=None,
                               num_parallel_tree=None, ...))])

## Model Evaluation

### Evaluate on test-set

In [44]:
# Make predictions on test-set

from sklearn.metrics import roc_auc_score

y_pred = best_model.predict(x_test)

roc_auc = roc_auc_score(y_test, y_pred)
print(roc_auc)

0.73945651261735

### Feature importances

In [45]:
xgbmodel=best_model.named_steps['model']
xgbmodel

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=np.float64(0.5945349994052989), device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, feature_weights=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None,
              learning_rate=np.float64(0.030853386772093122), max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=560, n_jobs=None,
              num_parallel_tree=None, ...)

In [46]:
df_importances = (
    pd.DataFrame({
        'columns': xgbmodel.feature_names_in_, 
        'importance': xgbmodel.feature_importances_
    })
    .sort_values('importance', ascending=False) 
)

# Preview data - we apply some formatting and table will be more visually appealing
df_importances.style.format({'importance': '{:.3%}'}).bar(subset=['importance'], color='#3498db').hide(axis='index')